# Markdown renderer configuration
[goldmark.renderer]
unsafe = true

[goldmark.extensions.passthrough]
enable = true

[goldmark.extensions.passthrough.delimiters]
block = [['$$', '$$'], ['\[', '\]'], ['\begin{equation}', '\end{equation}'], ['\begin{align}', '\end{align}'], ['\begin{align*}', '\end{align*}'], ['\begin{aligned}', '\end{aligned}'], ['\begin{gather}', '\end{gather}'], ['\begin{gather*}', '\end{gather*}']]
inline = [['$', '$'], ['\(', '\)']]

[tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4
