[build]
publish = "public"
command = "hugo --gc --minify -b ${URL}"

[build.environment]
HUGO_VERSION = "0.150.0"

[[redirects]]
  from = "http://podcast.tdhopper.com/*"
  to = "https://tdhopper.com/podcast/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://podcast.tdhopper.com/*"
  to = "https://tdhopper.com/podcast/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/podcast/feed"
  to = "https://anchor.fm/s/10e345fbc/podcast/rss"
  status = 200
  force = true
